$terminal = alacritty
$fileManager = nautilus
$browser = zen-browser
$discord = vesktop
$steam = steam
$ide = zeditor

exec-once = dbus-update-activation-environment --systemd HYPRLAND_INSTANCE_SIGNATURE
exec-once = hyprpm reload
exec-once = obs --startreplaybuffer
exec-once = ~/.local/share/applications/input-overlay-ws
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec = hyprshade auto
exec-once = bash -c 'source /etc/profile && quickshell'