source = ~/.config/hypr/autoexec.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/look.conf
source = ~/.config/hypr/env.conf

# See https://wiki.hypr.land/Configuring/Monitors/
monitor = DP-1, highres@highrr, auto, 1, bitdepth, 10
monitor = HDMI-A-1, highres@highrr, auto-right, 1, bitdepth, 10

general {
    layout = scrolling
    resize_on_border = false
}

plugin {
    hyprexpo {
        columns = 1
        gap_size = 3
        workspace_method = center
    }
}

scrolling {
    fullscreen_on_one_column = true
}

group {
    auto_group = false
}

# See https://wiki.hypr.land/Configuring/Permissions/
# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

windowrule = immediate set, match:class ^(dev.zed.Zed)$

windowrule = no_screen_share 1, match:class ^(zen)$

windowrule {
    name = force-window-main-screen
    match:class = ^(cs2)$ monitor HDMI-A-1
}

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 1
    disable_hyprland_logo = true
    allow_session_lock_restore = true
    vfr = false
}