# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = de
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 0
    sensitivity = 0
    accel_profile = flat

    scroll_method = on_button_down
    follow_mouse = 2

    touchpad {
        natural_scroll = false
    }
}

binds {
    workspace_back_and_forth = false
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

# See https://wiki.hypr.land/Configuring/Keywords/
$mod = super
$workspace = shift
$alt = ctrl

# special keybinds
bind = $mod, f4, killactive
bind = $mod, f11, fullscreen
bind = $mod, f12, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mod, f24, sendshortcut, , F24, class:^(com\.obsproject\.Studio)$
bind = $mod, super_L, hyprexpo:expo, toggle

bind = $mod, T, exec, $terminal
bind = $mod, E, exec, $fileManager
bind = $mod, B, exec, $browser
bind = $mod, Z, exec, $ide
bind = $mod, R, exec, fuzzel #TODO remove

bind = $mod, g, togglegroup
bind = $mod, up, changegroupactive, f
bind = $mod, down, changegroupactive, b
bind = $mod, comma, moveintogroup, l
bind = $mod, period, moveoutofgroup

bind = $mod, tab, workspace, e+1
bind = $mod $alt, tab, workspace, e-1
bind = $mod $workspace, left, movetoworkspace, e-1
bind = $mod $workspace, right, movetoworkspace, e+1

bind = $mod, left, layoutmsg, focus l
bind = $mod, right, layoutmsg, focus r
bind = $mod $alt, left, layoutmsg, swapcol l
bind = $mod $alt, right, layoutmsg, swapcol r

bind = $mod, V, togglefloating,
bindm = $mod, mouse:272, movewindow